SELECT T.FIID_TIPO_DOCTO
                     ,T.FCNOMBRE
                     ,P.FCNOMBREPAGINA
                     ,'http://10.51.230.89/' || P.FCALIAS || '/Acertum' 
                             || SUBSTR(P.FCRUTA
                                      ,LENGTH(P.FCRUTASOL)
                                      ,LENGTH(P.FCRUTA)) FCRUTA
                 FROM DIGBB.TADG_EXPCOMUN       E
           INNER JOIN DIGBB.TADG_DOCUMENTO      D ON E.FIIDGABINETE = D.FIIDGABINETE
           INNER JOIN DIGBB.TCDG_TIPO_DOCUMENTO T ON D.FIID_TIPO_DOCTO = T.FIID_TIPO_DOCTO
           INNER JOIN DIGBB.TADG_PAGINA         P ON E.FIIDGABINETE = P.FIIDGABINETE
                                              AND D.FIID_TIPO_DOCTO = P.FIID_TIPO_DOCTO
                                              AND D.FIIDPRODUCTO = P.FIIDPRODUCTO;

select *
from DIGBB.TADG_OPERACAPTA;

select *
from DIGBB.TADG_ACLARACION;

SELECT T.FIID_TIPO_DOCTO
     ,T.FCNOMBRE
     ,P.FCNOMBREPAGINA
     ,'http://10.51.230.89/' || P.FCALIAS || '/Acertum' 
             || SUBSTR(P.FCRUTA
                      ,LENGTH(P.FCRUTASOL)
                      ,LENGTH(P.FCRUTA)) FCRUTA
     ,E.FCCUENTA_AHORRO
     ,'1' || '-' || '1' || '-' || '1' || '-' || '1' CTE_UNICO
     ,E.FDFECHA_MOD
     ,E.NOMBRE
FROM (
        SELECT  E.FIIDGABINETE, NULL FCCUENTA_AHORRO, E.FCNOMBRE || ' ' || E.FCAPATERNO || ' ' || E.FCAMATERNO NOMBRE, NULL FDFECHA_MOD 
        FROM TADG_EXPCOMUN E 
        WHERE E.FIIDPAIS = TO_NUMBER('1') AND E.FIIDCANAL = TO_NUMBER('1') AND E.FIIDSUCURSAL = TO_NUMBER('1') AND E.FIFOLIO = TO_NUMBER('1')
        UNION
        SELECT  A.FIIDGABINETE, A.FCCUENTA_AHORRO, NULL NOMBRE, A.FDFECHA_MOD 
        FROM TADG_ACERTUM A 
        WHERE A.FIIDPAIS = TO_NUMBER('1') AND A.FIIDCANAL = TO_NUMBER('1') AND A.FIIDSUCURSAL = TO_NUMBER('1') AND A.FIFOLIO = TO_NUMBER('1') AND A.FCCUENTA_AHORRO = 1
     ) E
INNER JOIN DIGBB.TADG_DOCUMENTO      D ON E.FIIDGABINETE = D.FIIDGABINETE
INNER JOIN DIGBB.TCDG_TIPO_DOCUMENTO T ON D.FIID_TIPO_DOCTO = T.FIID_TIPO_DOCTO
INNER JOIN DIGBB.TADG_PAGINA         P ON E.FIIDGABINETE = P.FIIDGABINETE
                                   AND D.FIID_TIPO_DOCTO = P.FIID_TIPO_DOCTO
                                   AND D.FIIDPRODUCTO = P.FIIDPRODUCTO
     WHERE P.FIIDPRODUCTO IN(1, 2)
     order by T.FIID_TIPO_DOCTO
                     ;