SELECT CUENTA_AHORRO,CLIENTE_UNICO, FECHA_DIG ,TRIM(NOMBRE) || ' ' || TRIM(APATERNO) || ' ' || TRIM(AMATERNO) NOMBRE, ID_GABINETE
FROM IMAX.IMXCAPTACION
-- WHERE CUENTA_AHORRO = PACUENTA_AHORRO

;

SELECT DC.FCNOMBREDOCTO,
      D.FIIDTIPODOCTO,
      P.IDDOCUMENTO,
      (   'http://localhost/'
       || U.FCALIAS
       || '/'
       || REPLACE (V.RUTA_DIRECTORIO, '\', '/')
       || P.NOMBREPAGINA)
         RUTAHTTP
 FROM IMAX.TADGDOCCOMUN D
      INNER JOIN IMAX.TADGEXPPAGINA P
         ON     D.FIIDGABINETE = P.IDGABINETE
            AND D.FCTITULOAPLI = P.APLICACION
            AND D.FIIDDOCUMENTO = P.IDDOCUMENTO
      INNER JOIN IMAX.IMX_VOLUMEN V
         ON V.VOLUMEN = P.VOLUMEN
      INNER JOIN IMAX.IMX_UNIDAD_VOLUMEN U
         ON U.UNIDAD = V.UNIDAD_DISCO
      INNER JOIN IMAX.TCDGCATDOCCOMUN DC
         ON DC.FIIDTIPODOCTO = D.FIIDTIPODOCTO
--         WHERE     D.FIPAIS = PAPAIS
--               AND D.FICANAL = PACANAL
--               AND D.FISUCURSAL = PASUCURSAL
--               AND D.FIFOLIO = PAFOLIO
--               AND D.FCTITULOAPLI = PAAPLICA
--               AND DC.FIESTATUSDOC = PAESTATUS
ORDER BY DC.FIIDTIPODOCTO, P.IDPAGINA DESC
;

SELECT P.TITULO_APLICACION,D.NOMBRE_DOCUMENTO, D.ID_TIPO_DOCTO,P.ID_DOCUMENTO,( 'http://10.51.230.89/' || U.FCALIAS || '/' || REPLACE(V.RUTA_DIRECTORIO,'\','/') || P.NOM_ARCHIVO_VOL) RUTAHTTP
FROM IMAX.IMX_PAGINA P   INNER JOIN
     IMAX.IMX_DOCUMENTO D ON D.TITULO_APLICACION    = P.TITULO_APLICACION 
                         AND D.ID_GABINETE          = P.ID_GABINETE
                         AND D.ID_DOCUMENTO         = P.ID_DOCUMENTO
                         INNER JOIN
     IMAX.IMX_VOLUMEN V   ON V.VOLUMEN = P.VOLUMEN   
                         INNER JOIN
     IMAX.IMX_UNIDAD_VOLUMEN U ON U.UNIDAD = V.UNIDAD_DISCO                     
 WHERE P.TITULO_APLICACION = 'CAPTACION'
      AND P.ID_GABINETE       = 1
 --     AND P.STATUSIMX         = 1
 --     AND D.STATUSIMX         = 1    
ORDER BY D.ID_TIPO_DOCTO, P.NUMERO_PAGINA;  

--insert into IMAX.IMXCAPTACION values(3,'N','1-2-3456-7890','01234567890123','3','1234',SYSDATE,'CARLOS','CUAYA','CASTRO',1,'Guardadito',0,0,null,null,null,0);

update IMAX.IMXCAPTACION 
set CUENTA_AHORRO = '1', 
CLIENTE_UNICO = '1-1-1-1', 
FECHA_DIG = '20141028 10:59:29', 
NOMBRE = 'MIGUEL',
APATERNO = 'RGUEZ',
AMATERNO = 'TAPIA'
WHERE ID_GABINETE = 3
;
SELECT CURRENT_DATE
FROM DUAL
;

